/**
 * Centralized UI labels for all components, retrieved through the language store.
 */
export const LABELS = {
    nl: {
        header: {
            title: "Verken de Digital Twin",
            logout: "Uitloggen",
            loggingOut: "Uitloggen...",
            switchTwin: "Digital Twin",
            switchSimulation: "Simulatie",
            switchLanguage: "Taal",
        },
        login: {
            title: "DEEL Digital Twin",
            codeLabel: "Toegangscode",
            codePlaceholder: "Bijv. A1B2C-3D4E5",
            loginButton: "Inloggen",
            loggingIn: "Laden...",
            error: "De ingevoerde toegangscode is ongeldig of verlopen."
        },
        websocket: {
            notConnected: 'Niet verbonden met server',
            refresh: '⟳',
        },
        parameters: {
            carSpeed: "Auto snelheid",
            scenario: "Scenario's",
        },
        carTable: {
            header: "Auto's",
            status: "Status",
            carId: "Auto ID",
            energy: "Energie",
            packages: "Max. pakketten",
            route: "Route",
            routeVisibility: "Visualisatie",
            showRoute: "Toon",
            hideRoute: "Verberg",
        },
        controls: {
            simulationSpeed: "Simulatie snelheid",
            startButton: "Start",
            stopButton: "Stop",
        },
        generalStats: {
            title: "Statistieken",
            time: "Tijd",
            Score: "Score",
        },
        simStats: {
            emptyState: "Geen simulatiedata beschikbaar",
            loadingState: "Simulatiedata laden...",
            title: "Simulatie Statistieken",
            distance: "Afstand",
            drivingTime: "Rijtijd",
            packagesDelivered: "Bezorgde pakketten",
            totals: "Totalen",
            totalDistance: "Totale afstand",
            totalDrivingTime: "Totale rijtijd",
            totalPackages: "Totaal bezorgde pakketten",
            totalsSteps: "Stappen",
            downloadCsv: "Download CSV",
            downloadingCsv: "Bezig met downloaden...",
            statsRetrievalError: "Fout bij het ophalen van statistieken",
            statsCsvError: "Fout bij het downloaden van CSV",
        },
        impactStats: {
            title: "Statistieken",
            surroundings: "Omgeving",
            economy: "Economie",
            social: "Sociaal",
            energy: "Energie",
            safety: "Veiligheid",
            maintainability: "Onderhoudbaarheid",
            total: "Totale score",
            download: "Download CSV",
            category: "Categorie",
            score: "Score",
        },
        rfidTags: {
            title: "RFID Tags",
            id: "ID",
            positions: "Posities",
            showTags: "Toon",
            hideTags: "Verberg",
        },
        simScenarios: {
            calm: "Rustig",
            average: "Gemiddeld",
            busy: "Druk",
        },
        simRoutes: {
            inactive: "Inactief",
            short_1: "Kort 1",
            short_2: "Kort 2",
            short_3: "Kort 3",
            short_4: "Kort 4",
            short_5: "Kort 5",
            short_6: "Kort 6",
            medium_1: "Gemiddeld 1",
            medium_2: "Gemiddeld 2",
            medium_3: "Gemiddeld 3",
            medium_4: "Gemiddeld 4",
            medium_5: "Gemiddeld 5",
            long_1: "Lang 1",
            long_2: "Lang 2",
            long_3: "Lang 3",
            long_4: "Lang 4",
            long_5: "Lang 5",
        },
        simSpeed: {
            '1': "1x",
            '2': "5x",
            '3': "10x",
            '4': "Maximaal",
        },
        adminHeader: {
            title: "Admin paneel",
            subTitle: "Admin inloggen en toegangscodes beheren",
            back2Login: "Terug naar inloggen",
        },
        adminLogin: {
            loginTitle: "Admin inloggen",
            usernameLabel: "Gebruikersnaam",
            passwordLabel: "Wachtwoord",
            loginButton: "Inloggen",
            loggingIn: "Laden...",
            error: "De ingevoerde gebruikersnaam of wachtwoord is ongeldig.",
        },
        adminCode: {
            new: "Nieuwe code maken",
            description: "Vul de naam van de groep in en kies wanneer de code verloopt. Na aanmaken verschijnt de code direct in beeld.",
            codeLabel: "Naam (bijv. Groep A)",
            expiresLabel: "Verloopt over",
            codeButton: "Aanmaken",
            copyNewCode: "Kopieer en deel deze code",
            newCodeDescription: "Deze code wordt maar eenmalig weergegeven.",
        },
        adminManage: {
            title: "Bestaande codes beheren",
            description: "Selecteer codes om ze in bulk te verlengen of te verwijderen.",
            selectAll: "Alles selecteren",
            groupExtend: "Bulk verlengen",
            groupDelete: "Bulk verwijderen",
            tableId: "#",
            tableName: "Naam",
            tableExpires: "Vervalt op",
            tableStatus: "Status",
            tableActions: "Acties",
            codeRevoked: "Ingetrokken",
            codeExpired: "Verlopen",
            codeActive: "Actief",
            codeRevoke: "Intrekken",
            codeExtend: "Verlengen",
            codeDelete: "Verwijderen",
        },
        misc: {
            closeButton: "x",
        },
    },
    en: {
        header: {
            title: "Explore the Digital Twin",
            logout: "Logout",
            loggingOut: "Logging out...",
            switchTwin: "Digital Twin",
            switchSimulation: "Simulation",
            switchLanguage: "Language",
        },
        login: {
            title: "DEEL Digital Twin",
            codeLabel: "Access Code",
            codePlaceholder: "E.g. A1B2C-3D4E5",
            loginButton: "Login",
            loggingIn: "Loading...",
            error: "The entered access code is invalid or expired.",
        },
        websocket: {
            notConnected: 'Not connected to server',
            refresh: '⟳',
        },
        parameters: {
            carSpeed: "Car speed",
            scenario: "Scenarios",
        },
        carTable: {
            header: "Cars",
            status: "Status",
            carId: "Car ID",
            energy: "Energy",
            packages: "Max. packages",
            route: "Route",
            routeVisibility: "Visibility",
            showRoute: "Show",
            hideRoute: "Hide",
        },
        controls: {
            simulationSpeed: "Simulation Speed",
            startButton: "Start",
            stopButton: "Stop",
        },
        generalStats: {
            title: "Statistics",
            time: "Time",
            Score: "Score",
        },
        simStats: {
            emptyState: "No simulation data available",
            loadingState: "Loading simulation data...",
            title: "Simulation Statistics",
            distance: "Distance",
            drivingTime: "Driving time",
            packagesDelivered: "Packages delivered",
            totals: "Totals",
            totalDistance: "Total distance",
            totalDrivingTime: "Total driving time",
            totalPackages: "Total packages delivered",
            totalsSteps: "Steps",
            downloadCsv: "Download CSV",
            downloadingCsv: "Downloading...",
            statsRetrievalError: "Error occurred while retrieving statistics",
            statsCsvError: "Error occurred while downloading CSV",
        },
        impactStats: {
            title: "Statistics",
            surroundings: "Surroundings",
            economy: "Economy",
            social: "Social",
            energy: "Energy",
            safety: "Safety",
            maintainability: "Maintainability",
            total: "Combined score",
            download: "Download CSV",
            category: "Category",
            score: "Score",
        },
        rfidTags: {
            title: "RFID Tags",
            id: "ID",
            positions: "Positions",
            showTags: "Show",
            hideTags: "Hide",
        },
        simScenarios: {
            calm: "Calm",
            average: "Average",
            busy: "Busy",
        },
        simRoutes: {
            inactive: "Inactive",
            short_1: "Short 1",
            short_2: "Short 2",
            short_3: "Short 3",
            short_4: "Short 4",
            short_5: "Short 5",
            short_6: "Short 6",
            medium_1: "Medium 1",
            medium_2: "Medium 2",
            medium_3: "Medium 3",
            medium_4: "Medium 4",
            medium_5: "Medium 5",
            long_1: "Long 1",
            long_2: "Long 2",
            long_3: "Long 3",
            long_4: "Long 4",
            long_5: "Long 5",
        },
        simSpeed: {
            '1': "1x",
            '2': "5x",
            '3': "10x",
            "4": "Maximum",
        },
        adminHeader: {
            title: "Admin panel",
            subTitle: "Admin login and manage access codes",
            back2Login: "Back to login",
        },
        adminLogin: {
            loginTitle: "Admin login",
            usernameLabel: "Username",
            passwordLabel: "Password",
            loginButton: "Login",
            loggingIn: "Loading...",
            error: "The entered username or password is invalid.",
        },
        adminCode: {
            new: "Create new code",
            description: "Enter the name of the group and choose when the code expires. After creation, the code will be displayed immediately.",
            codeLabel: "Name (e.g. Group A)",
            expiresLabel: "Expires in",
            codeButton: "Create",
            copyNewCode: "Copy and share this code",
            newCodeDescription: "This code will only be displayed once.",
        },
        adminManage: {
            title: "Manage existing codes",
            description: "Select codes to extend or delete them in bulk.",
            selectAll: "Select all",
            groupExtend: "Bulk extend",
            groupDelete: "Bulk delete",
            tableId: "#",
            tableName: "Name",
            tableExpires: "Expires on",
            tableStatus: "Status",
            tableActions: "Actions",
            codeRevoked: "Revoked",
            codeExpired: "Expired",
            codeActive: "Active",
            codeRevoke: "Revoke",
            codeExtend: "Extend",
            codeDelete: "Delete",
        },
        misc: {
            closeButton: "x",
        },
    },
};
