; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_port = COM4
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8
	miguelbalboa/MFRC522@^1.4.12
	madhephaestus/ESP32Servo@^3.0.9
	adafruit/Adafruit MLX90393@^2.0.5
	sparkfun/SparkFun TB6612FNG Motor Driver Library@^1.0.0

; Pre-build script to validate environment configuration
extra_scripts = pre:scripts/env_mgr.py

; Load configurations from .env file
build_flags = 
    -D CFG_WIFI_SSID=\"${sysenv.DEEL_WIFI_SSID}\"
    -D CFG_WIFI_PSK=\"${sysenv.DEEL_WIFI_PSK}\"
    -D CFG_BROKER_HOST=\"${sysenv.DEEL_SERVER_IP}\"
    -D CFG_PSK_HEX=\"${sysenv.DEEL_SERVER_PSK}\"
