# Local (Unix socket) connections require a password as well.
local   all             all                                     scram-sha-256

# Allow TLS connections from anywhere inside Docker networks.
hostssl all             all             0.0.0.0/0               scram-sha-256
hostssl all             all             ::/0                    scram-sha-256

# Explicitly reject non-TLS TCP connections.
hostnossl all           all             0.0.0.0/0               reject
hostnossl all           all             ::/0                    reject
